[package]
name = "liaise"
version = "0.1.0"
edition = "2024"


license = "MIT OR Apache-2.0"
description = "diagnostic error propagation"

authors = ["James Hunt <jameshuntdevelopment@gmail.com>"]
repository = "https://github.com/jameshuntt/liaise"

readme = "readme.md"

[dependencies]
